POST https://api.openai.com/v1/chat/completions
Content-Type: application/json
Authorization: Bearer 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

{
  "model" : "gpt-3.5-turbo-16k",
  "messages": [
    {"role": "user", "content": "10 2층 건물 규모의 첨단장비에서 암세포만 골라 파기하는 중 입자가 만들어집니다 중 읽지 않은 3D 엑스레이로 설정 잡혀 있더라 환자에게 전달됩니다 1밀리미터의 사용 하지 않기 위해 환자의 몸을 본뜬 장치로 골반과 발을 고정하고 소변 장내가스 양도 측정합니다 오늘 저녁 한 그릇 맞다고 생각이 들면 그때 이제 입력이 되고 시작하겠습니다 진행된 시간은 고장 2분 환자는 전혀 고통을 느끼지 못했습니다 만드실 때 아무도 없었습니다 세브란스병원은 이런 방식으로 1주마다 세 번씩 총 12번으로 완료되는 전립선암치료 1차 성적표를 공개했습니다 전립선암 있던 자리가 수술 한 것처럼 사라졌는데 세브란스병원 70여명의 전립선암환자에서 암세포가 사라졌고 암혈에 수치도 정산 중대 합병증은 없었다고 밝혔습니다 또 다른 방에서 진행 중인 회전형 중입자 빔 공사 중이다 빔을 도착하면 3층 건물 규모의 발생장치가 또 있음 내년 상반기에 공사까지 완료되면 췌장암 간암에 폐암 등 숭실대 움직이는 장기의 암도 치료할 수 있습니다 대장암은 기존의 방사선치료나 항암치료도 굉장히 잘 안된다는 난치성 암으로 가방 같은 경우에는 예를 들어서 간경화 라든지 간 기능이 약화된 환자분들은 차도가 없는 환자들을 우선 치료 대상으로 정하기로 했습니다 치료비용은 5천만 원 정도인데 높은 비용과 대기순서 때문에 현재로선 중입자치료를 기다리는 것보단 표준 치료를 받는게 현실적일 수 있습니다 SBS 자동차입니다\n"},
    {"role": "system", "content": "당신은 스크립트를 요약해야 합니다.\n제공하는 글을 대상으로 중요한 내용을 여러 문장으로 요약하세요.\n요구사항은 아래와 같습니다.\n1. 요약된 문장들은 한글로 작성되어야 합니다.\n2. 요약된 문장들은 '*'로 시작되어야 합니다.\n"}
  ],
  "temperature": 0.2,
  "max_tokens" : 6000
}
